use std::io;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use clap::{Parser, Subcommand};
use hex;
use methods::{GUEST_CODE_FOR_ZK_PROOF_ELF, GUEST_CODE_FOR_ZK_PROOF_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, Receipt};
use k256::PublicKey;
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use musig2::secp::Scalar;

#[derive(Debug, Parser)]
#[command(name = "zk-musig")]
#[command(about = "Zero-knowledge proof generation and verification for MuSig2", long_about = None)]
#[command(version)]
struct Args {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Generate a zero-knowledge proof for MuSig2 signature
    Prove {
        /// Configuration JSON string or path to config file (use @file.json for file input)
        #[arg(short, long)]
        config: String,

        /// Proof type to generate
        #[arg(short = 't', long, value_name = "TYPE")]
        #[arg(value_parser = ["default", "fast", "succinct", "groth16", "composite"])]
        proof_type: Option<String>,
    },
    /// Verify a zero-knowledge proof
    Verify {
        /// Hex-encoded proof to verify (reads from stdin if not provided)
        #[arg(short, long)]
        proof: Option<String>,
    },
}

#[derive(Deserialize, Serialize, Debug, Clone)]
struct Config {
    pub coeff_salt: String,
    pub blinding_factors: Vec<(String, String, String)>,
    pub pubkeys: Vec<String>,
    pub pubnonces: Vec<String>,
    pub message: String,
    pub signer_index: usize,
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let args = Args::parse();

    match args.command {
        Commands::Verify { proof } => {
            verify_proof(proof);
        }
        Commands::Prove { config, proof_type } => {
            generate_proof(config, proof_type);
        }
    }
}

fn verify_proof(proof_hex: Option<String>) {
    let hex_string = match proof_hex {
        Some(p) => p,
        None => {
            // Read from stdin
            let mut buffer = String::new();
            io::stdin().read_line(&mut buffer).unwrap();
            buffer.trim().to_string()
        }
    };

    let bin = hex::decode(hex_string.trim()).unwrap();
    let receipt: Receipt = bincode::deserialize(&bin).unwrap();
    receipt.verify(GUEST_CODE_FOR_ZK_PROOF_ID).unwrap();
    println!("verified");
}

fn generate_proof(config_input: String, proof_type: Option<String>) {
    let cfg: Config = serde_json::from_str(&config_input).unwrap();

    let coeff_salt: [u8; 32] = hex::decode(cfg.coeff_salt).unwrap().try_into().unwrap();

    let blinding_factors: Vec<([u8;32], [u8;32], [u8;32])> = cfg
        .blinding_factors
        .iter()
        .map(|(alpha, beta, gamma)| {
            (
                Scalar::from_str(alpha).unwrap().into(),
                Scalar::from_str(beta).unwrap().into(),
                Scalar::from_str(gamma).unwrap().into(),
            )
        })
        .collect();

    let pubkeys: Vec<PublicKey> = cfg.pubkeys.iter().map(|pk| parse_pubkey(pk)).collect();

    let input: usize = 0;
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .write(&coeff_salt)
        .unwrap()
        .write(&pubkeys)
        .unwrap()
        .write(&blinding_factors)
        .unwrap()
        .write(&cfg.pubnonces)
        .unwrap()
        .write(&cfg.message)
        .unwrap()
        .build()
        .unwrap();

    let prover_opts: ProverOpts = match proof_type.as_deref() {
        None | Some("default") => {
            println!("using default proof type");
            ProverOpts::default()
        }
        Some("fast") => {
            println!("using fast proof type");
            ProverOpts::fast()
        }
        Some("succinct") => {
            println!("using succinct proof type");
            ProverOpts::succinct()
        }
        Some("groth16") => {
            println!("using groth16 proof type");
            ProverOpts::groth16()
        }
        Some("composite") => {
            println!("using composite proof type");
            ProverOpts::composite()
        }
        _ => {
            println!("proof type invalid");
            return;
        }
    };

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove_with_opts(env, GUEST_CODE_FOR_ZK_PROOF_ELF, &prover_opts)
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // Decode journal data
    let _pubkey: String = receipt.journal.decode().unwrap();
    let _pubnonce: String = receipt.journal.decode().unwrap();
    let _challenge_parity: u8 = receipt.journal.decode().unwrap();
    let _nonce_parity: u8 = receipt.journal.decode().unwrap();
    let _b: String = receipt.journal.decode().unwrap();
    let _e: String = receipt.journal.decode().unwrap();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(GUEST_CODE_FOR_ZK_PROOF_ID).unwrap();

    let receipt_bytes = bincode::serialize(&receipt).unwrap();
    println!("{}", hex::encode(receipt_bytes));
}

fn parse_pubkey(pub_str: &str) -> PublicKey {
    let pk_bytes = hex::decode(pub_str).unwrap();
    let pk = PublicKey::from_sec1_bytes(&pk_bytes).unwrap();

    println!("sec1 pub: {}", hex::encode(pk_bytes));

    pk
}
